---
- hosts: all
  become: yes
  tasks:
    - name: Install aptitude if missing
      apt:
        update_cache: yes
        name: "aptitude"
        state: latest

    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Update apt packaages
      apt:
        name: "*"
        state: latest

    - name: Autoremove apt packages
      apt:
        autoremove: yes

    - name: Autoclean apt packages
      apt:
        autoclean: yes

    - name: Automate this in cron
      cron:
        name: "Run maintenance"
        minute: 0
        hour: "2"
        job: "ansible-pull -U https://github.com/ssccio/ansible-ubuntu-maintenance -i hosts"

    - name: Set EDITOR to vim in /etc/profile
      lineinfile:
        path: /etc/profile
        line: export EDITOR=vim
